// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 

    public static final int left1ID = 2;
    public static final int left2ID = 4;
    public static final int left3ID = 6;
    public static final int right1ID = 3;
    public static final int right2ID = 5;
    public static final int right3ID = 7;
    public static final int rTalonID = 8;
    public static final int leftHookID = 10;
    public static final int rightHookID = 9;
    //public static final int softwareBraincells = 0;

    /*
    public static final int ripleyLMID = 10;
    public static final int ripleyLF1ID = 12;
    public static final int ripleyLF2ID = 14;
    public static final int ripleyRMID = 11;
    public static final int ripleyRF1ID = 13;
    public static final int ripleyRF2ID = 15;
    */
}