// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Robot;
import frc.robot.RobotMap;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;



/**
 *
 */
public class ClipSubsystem extends SubsystemBase {

    private DoubleSolenoid leftPiston;
    private DoubleSolenoid rightPiston;
    private Compressor compressor;
    
    /**
    *
    */
    public ClipSubsystem() {

        leftPiston = RobotMap.leftPiston;
        addChild("leftPiston", leftPiston);
        rightPiston = RobotMap.rightPiston;
        addChild("rightPiston", rightPiston); 

    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
    
    public void pistonsForward() {
        leftPiston.set(Value.kForward);
        rightPiston.set(Value.kForward);
    }

    public void pistonsReverse() {
        leftPiston.set(Value.kReverse);
        rightPiston.set(Value.kReverse);
    }

    public void pistonsOff() {
        leftPiston.set(Value.kOff);
        rightPiston.set(Value.kOff);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

