// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.RobotContainer;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.XboxController;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.PWMTalonFX;
import edu.wpi.first.wpilibj.motorcontrol.PWMTalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMTalonFX left1;
private PWMTalonFX left2;
private PWMTalonFX left3;
private MotorControllerGroup leftMotors;
private PWMTalonFX right1;
private PWMTalonFX right2;
private PWMTalonFX right3;
private MotorControllerGroup rightMotors;
private DifferentialDrive drive;

private PWMTalonSRX testleft1;
private PWMTalonSRX testright1;
private PWMTalonSRX testleft2;
private PWMTalonSRX testright2;
private PWMTalonSRX testleft3;
private PWMTalonSRX testright3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
left1 = new PWMTalonFX(0);
 addChild("left1",left1);
 left1.setInverted(false);

left2 = new PWMTalonFX(1);
 addChild("left2",left2);
 left2.setInverted(false);

left3 = new PWMTalonFX(3);
 addChild("left3",left3);
 left3.setInverted(false);

leftMotors = new MotorControllerGroup(left1, left2 , left3 );
 addChild("leftMotors",leftMotors);
 

right1 = new PWMTalonFX(4);
 addChild("right1",right1);
 right1.setInverted(true);

right2 = new PWMTalonFX(5);
 addChild("right2",right2);
 right2.setInverted(true);

right3 = new PWMTalonFX(6);
 addChild("right3",right3);
 right3.setInverted(true);

rightMotors = new MotorControllerGroup(right1, right2 , right3 );
 addChild("rightMotors",rightMotors);
 

drive = new DifferentialDrive(leftMotors, rightMotors);
 addChild("Drive",drive);
 drive.setSafetyEnabled(true);
drive.setExpiration(0.1);
drive.setMaxOutput(1.0);



        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    public void arcadeDrive() {
		drive.arcadeDrive(-RobotContainer.getdriveStick().getLeftY(), RobotContainer.getdriveStick().getLeftX());
	}

    public void tankDrive() {
		leftMotors.set(RobotContainer.getdriveStick().getLeftY());
		rightMotors.set(RobotContainer.getdriveStick().getRightY());
	}

    /*public void tankDrive(double leftVal, double rightVal) {
		leftMotors.set(ControlMode.PercentOutput, leftVal);
		rightMotors.set(ControlMode.PercentOutput, rightVal);
	}*/

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
